version: '3.8'
services:
  truebank:
    build: .
    container_name: truebank-app
    stdin_open: true
    tty: true
    image: truebank:latest
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=truebank
      - DB_USER=truebankuser
      - DB_PASS=truebankpass
    command: ["tail", "-f", "/dev/null"]
